### ISSUE TITLE
Decorator for Mixin support?

### ISSUE THREAD

**Issue by Kerrick** [ember-decorators/ember-decorators#115]
Congrats on launching `ember-decorators` as a successor to `ember-computed-decorators`!

I was looking through [the docs](https://rwjblue.github.io/ember-decorators/docs/index.html) and I don't see anything about how to handle Mixins. Am I missing it, or is this addon missing that feature?

Here's how I think it could look, if this issue turns out to be a feature request:

```js
import Ember from 'ember';
import RendersIntoApplication from 'my-app/mixins/renders-into-application';
import AuthenticatedRouteMixin from 'ember-simple-auth/mixins/authenticated-route-mixin';

export default Ember.Route.extend(RendersIntoApplication, AuthenticatedRouteMixin, {
  foo: Ember.inject.service()
});
```

```js
import Ember from 'ember'
import { mixin } from 'ember-decorators/object';
import { service } from 'ember-decorators/service';
import RendersIntoApplication from 'my-app/mixins/renders-into-application';
import AuthenticatedRouteMixin from 'ember-simple-auth/mixins/authenticated-route-mixin';

@mixin(RendersIntoApplication, AuthenticatedRouteMixin)
export default class MyComponent extends Ember.Route {
  @service foo
}
```

**Comment by rwjblue** [comment]
The proposed syntax looks nice, but I don't really think we should support `Ember.Mixin`s in a `class Foo extends Ember.Object {}` scenario. It would be fairly easy to detect an `Ember.Mixin`, but it is not clear at all how to actually mix it in (via public API) when using `class ... extends {}` syntax...

If we add `@mixin` I would like for it to support class mixins with "real" `super` capabilities (ala [this blog post](http://justinfagnani.com/2015/12/21/real-mixins-with-javascript-classes/)).

**Comment by rwjblue** [comment]
Definitely up for more earnest discussion on the subject though....

**Comment by pzuraq** [comment]
I'm currently hesitant to add mixin support as well. Class decorators aren't really fully baked yet, I think they're the most in flux part of the proposal at the moment (seems semantics have changed greatly between stage 1 and stage 2). 

I also think that something more generic might come along, or even be proposed to actually be part of the language. This problem is definitely not Ember specific, so we may want to wait and see what other patterns emerge as ES classes become more popular and class decorators more used.

**Comment by BryanCrotaz** [comment]
What's the current way to use (eg) `ember-concurrency` with ES6 classes?

**Comment by danielspaniel** [comment]
@Kerrick .. and company .. I agree that the mixing of ember mixins and Ember Objecty classes is alittle weird, and the super style mixins you linked to would be nice. Problem is, we live in the here and now and people who are using class based Routes, Component and Controllers are using mixins. So, in the meantime that things get more perfect and the roses are all smelling rosy, and dancing fairies are all hanging out on our decorated classes, here is a decorator you can use to get the mixin support 

```js
/**
 * Class level decorator that adds mixins to a class
 *
 *
 * ```javascript
 * import MyMixin1 from '../mixins/my-mixin-one;
 * import MyMixin2 from '../mixins/my-mixin-two;
 *
 * @mixin([MyMixin1, MyMixin2])
 * export default class extends Model {
 *
 * }
 * ```
 *
 * @function
 * @param {Array} [mixins] -  Array of Ember Mixin's
 */
export function mixin(mixins) {
  return function decorator(target) {
    mixins.forEach(mixin => {
      let {properties}             = Object.assign({}, mixin.mixins[0]),
          {actions: mixinActions}  = properties,
          {actions: targetActions} = target.prototype;

      // merge mixin actions into target actions
      if (mixinActions) {
        Object.assign(targetActions, mixinActions)
      }
      // remove mixin actions key, since it will override target actions
      delete properties['actions'];
      Object.assign(target.prototype, properties);
    });
  };
}
```

**Comment by thec0keman** [comment]
For those of us looking for a transitionary approach, does this seem reasonable, or are the side effects to be aware of?

```
import Route from '@ember/routing/route';
import MyMixin1 from 'foo'
import MyMixin2 from 'bar'

const SuperClass = Route.extend(MyMixin1, MyMixin2);

export default class MyRoute extends SuperClass {\
}
```

**Comment by pzuraq** [comment]
@thec0keman That is the recommended approach. You can also do it with an anonymous class:

```js
export default class MyRoute extends Route.extend(MyMixin1, MyMixin2) {}
```

**Comment by Kerrick** [comment]
I'm [quite happy](https://github.com/tc39/proposal-pipeline-operator/pull/45) to see Ember mixing moving towards `|>`! 👏

**Comment by bastimeyer** [comment]
Sorry for hijacking this thread, but regarding using *the old `.extend` syntax*, this doesn't seem to work when you're trying to extend from a native class which itself is extending from EmberObject. The ember-decorators website says that this is possible after upgrading to Ember 3.2 and implies that this is how mixins can be used, but it's clearly not working.
See this ember-twiddle:
https://canary.ember-twiddle.com/b365ecfbc29444455d082cf1b295156b?openFiles=tests.foo-test.js%2C
Or am I doing something wrong here?

https://ember-decorators.github.io/ember-decorators/latest/docs/native-class-basics#extending-native-classes-with-extend-

> As of Ember v3.2, you can extend interoperably back and forth between native classes and EmberObject style extends
> ```js
> class Foo extends EmberObject {
>   // ...
> }
> 
> const Bar = Foo.extend({
>   // ...
> });
> 
> class Baz extends Bar {
>   // ...
> }
> ```

**Comment by rwjblue** [comment]
@bastimeyer - Please create a new issue for discussion of that, definitely worth digging into and properly clarifying...

**Comment by bastimeyer** [comment]
@rwjblue On the Ember repo?
