### ISSUE TITLE
@concatenated and @merged decorators

### ISSUE THREAD

**Issue by buschtoens** [ember-decorators/ember-decorators#135]
Breaking out from #133.

[`Ember.CoreObject`](https://www.emberjs.com/api/ember/2.14/classes/Ember.CoreObject) has two "magic" properties:

#### [`concatenatedProperties`](https://www.emberjs.com/api/ember/2.14/classes/Ember.CoreObject/properties/concatenatedProperties?anchor=concatenatedProperties)

> Defines the properties that will be concatenated from the superclass (instead of overridden).
>
> By default, when you extend an Ember class a property defined in the subclass overrides a property with the same name that is defined in the superclass. However, there are some cases where it is preferable to build up a property's value by combining the superclass' property value with the subclass' value. An example of this in use within Ember is the `classNames` property of `Ember.View`.

#### [`mergedProperties`](https://www.emberjs.com/api/ember/2.14/classes/Ember.CoreObject/properties/mergedProperties?anchor=mergedProperties)

> Defines the properties that will be merged from the superclass (instead of overridden).
>
> By default, when you extend an Ember class a property defined in the subclass overrides a property with the same name that is defined in the superclass. However, there are some cases where it is preferable to build up a property's value by merging the superclass property value with the subclass property's value. An example of this in use within Ember is the `queryParams` property of routes.

Currently concatenated / merged properties don't work with ES6 classes, as [Babel transpiles class properties in such a way that the concatenated / merged properties are overwritten](https://github.com/rwjblue/ember-decorators/issues/123#issuecomment-314763506) after the [base class's constructor that is responsible for concatenating / merging](https://github.com/emberjs/ember.js/blob/v2.14.1/packages/ember-runtime/lib/system/core_object.js#L81-L82) is called.

The consensus is, that this actually can be used to our advantage. We want to push for deprecating the magic `concatenatedProperties` and `mergedProperties` in favor of explicit `@concatenated` and `@merged` decorators. Arguments discussing the pro and cons can be found in #133.

We will treat using an ES6 class as an opt-in for this behavior.

#### `@concatenated`

```js
import Component from '@ember/component';
import { concatenated } from 'ember-decorators/object';

class BaseComponent extends Component {
  classNames = ['foo'];
}

class ConcatenatingComponent extends BaseComponent {
  @concatenated classNames = ['bar']; // => ['foo', 'bar'];
}

class OverwritingComponent extends ConcatenatingComponent {
  classNames = ['quux']; // => ['quux']
}
```

<sup>Note: usage of `Component` is purely for illustrational purposes. There's actually a plan for specialized decorators like `@className` and `@attribute` in #133.</sup>

#### `@merged`

```js
import Route from '@ember/routing/route';
import { merged } from 'ember-decorators/object';

class BaseRoute extends Route {
  queryParams = {
    page: { refreshModel: true }
  };
}

class MergingRoute extends BaseRoute {
  @merged queryParams = {
    filter: { refreshModel: true }
  }; // => { page, filter }
}

class OverwritingRoute extends MergingRoute {
  queryParams = {
    color: { refreshModel: true }
  }; // => { color }
}
```

**Comment by pzuraq** [comment]
This has been debated in the [ES Classes RFC](https://github.com/emberjs/rfcs/pull/240), currently the proposal is that merged and concatenated properties should be fixed and made to work as normal in ES Classes, and a separate RFC should be added in the future to deprecate them. If that proposal is accepted I think we should drop the `merged` and `concatenated` decorators for now in favor of the ones proposed in #133, which will still be useful if the old behavior is restored.

**Comment by pzuraq** [comment]
`@concatenated` and `@merged` have been added in [utility-decorators](https://github.com/ember-decorators/utility-decorators)
