### ISSUE TITLE
Overwrite default blueprints with ES6 classes version

### ISSUE THREAD

**Issue by buschtoens** [ember-decorators/ember-decorators#142]
https://github.com/rwjblue/ember-decorators/pull/137#discussion_r129353784

> We should consider adding some blueprints that generate the new style and would add the classname. Definitely agree that we should use realistic class names

I would suggest that the name for classes should be `<LastPathSegment><Type>`, in order to avoid absurdly long class names for nested classes. At least for components, since Module Unification will disallow nested components anyway (local lookup components are a different thing).

What about routes, controllers, etc? Should the name also be just `<LastPathSegment><Type>` or should we use the full path?

```js
// app/components/user-table/user-avatar/component.js
// ember g component user-table/user-avatar
import Component from '@ember/component';

export default class UserAvatarComponent extends Component {

}
```

```js
// app/profile/likes/route.js
// ember g route profile/likes
import Route from '@ember/routing/route';

export default class LikesRoute extends Component {

}
```

**Comment by pzuraq** [comment]
I agree regarding components that we should use last path segment. For routes/controllers it's tricky, since there could be duplicate class names introduced (`IndexController/Route`, etc.) which could be confusing. 

To be fair, users can name the classes whatever they want, so if they don't like the default they can change it.

**Comment by buschtoens** [comment]
You can also have nested components that have the same last path segment as other nested components. So you'll run into the same problem. 

But I think that this is an engineering problem, that should be solved by the doc generator, i.e. it should take the directory structure into account.

Looking at this repo, ESDoc appears to do so. YUIDoc uses `@module` tags for hierarchy. I don't know about JSDoc and TypeDoc. But I wanted to give the latter one another try, seeing that they seemed to have fixed some blocking issues. 

Anyways, still:

> To be fair, users can name the classes whatever they want, so if they don't like the default they can change it.

Maybe we can even make the name generation configurable / hookable, or do you think that's a bit over-engineered?

**Comment by pzuraq** [comment]
I think for now it's over-engineered, we should pick one and go with it and see what people prefer in the wild. I'd want to see what @rwjblue thinks, but I'd consider updating blueprints to do a different style in the future would not be a breaking change, so we could switch if users didn't like our pick.

**Comment by chilicoder** [comment]
Any updates here? Is it possible to prepare blueprints to be able to create both versions (one according to some configuration)?

**Comment by pzuraq** [comment]
Unfortunately blueprints aren't the highest priority at the moment, but I should be able to get some time to work on them after the holidays. PRs definitely welcome!

**Comment by allthesignals** [comment]
I started a branch here: https://github.com/allthesignals/ember-decorators/tree/142-es6-classes-blueprint-components. Need to update it to use LastPathSegment and Type, which seems like something we get for free in the blueprints.

**Comment by allthesignals** [comment]
Starting a list if anyone else wants to take a stab. I'll start with component generator. 

TODOs:
- [ ] support generate commands
  - [ ] ember generate component (🔒@allthesignals)
  - [ ] ember generate controller
  - [ ] ember generate route
  - [ ] ember generate service 
  - [ ] ember generate helper 
  - [ ] ember generate initializer
  - [ ] ember generate instance-initializer
  - [ ] ember generate mixin
  - [ ] ember data blueprints...
  - [ ] ...

@chilicoder interested? It's pretty easy to port this stuff over.

**Comment by chilicoder** [comment]
would like to try 
I'm [comparing](https://github.com/ember-decorators/ember-decorators/compare/master...allthesignals:142-es6-classes-blueprint-components)
your commits
did I get it right, lets say for `controller ` I will need to provide smth same (excluding `blueprints/module-unification.js`) ?

**Comment by allthesignals** [comment]
> Looking at this repo, ESDoc appears to do so. YUIDoc uses @module tags for hierarchy. I don't know about JSDoc and TypeDoc. But I wanted to give the latter one another try, seeing that they seemed to have fixed some blocking issues.

How does Rails handle this? I've seen some pretty long and wonky class names in generated snippets for Rails projects. Does the length really get so out of control? Maybe we'll need a hook to check for this and warn, otherwise users'll get broken development environment.

**Comment by pzuraq** [comment]
Yeah, I think we should probably go with full paths for now. Duplicate class names can actually cause even more problems in the wild, if you have two `IndexController` classes and you try to do memory profiling they'll collide, etc.

**Comment by chilicoder** [comment]
Ill try to do controller

**Comment by chilicoder** [comment]
Looks like we only need to update blueprint files (see my PR #210 ) to make it work

also checked 
* helper
* initializer
* initializer-addon
* initializer-instance
* util

blueprint for `mixin` has
```
export default Mixin.create({
});
```
which I don't know how to change

**Comment by chilicoder** [comment]
Also added PR #211 with blueprints for `ember-data`
Model is pretty sophisticated

**Comment by allthesignals** [comment]
@chilicoder awesome. Did you take on controller?

**Comment by chilicoder** [comment]
@allthesignals #210

**Comment by allthesignals** [comment]
@chilicoder thanks, I'm updating [this comment](https://github.com/ember-decorators/ember-decorators/issues/142#issuecomment-378636167) to reflect those

**Comment by chilicoder** [comment]
Basically, with #210 #218 and #211 we have all generators done. Mixins use .create()
