### ISSUE TITLE
[Documentation] The import syntax on the docs are incorrect

### ISSUE THREAD

**Issue by optikalefx** [ember-decorators/ember-decorators#155]
At the top of each definition on the docs page, it has the correct syntax

`import {alias} from 'ember-decorators/object/computed'`

However, right below that in the example is an incorrect example

`import { alias } from 'ember-decorators/computed';`

**Comment by buschtoens** [comment]
Thank you for reporting this. A PR would be much appreciated. :)

**Comment by spruce** [comment]
This is fixed inside the inline comments in the files. See https://github.com/ember-decorators/ember-decorators/blob/master/addon/object/computed.js#L13-L31
But the Docs should be updated.

**Comment by rwjblue** [comment]
The inline comments are used to generate the API docs website. Seems like we probably need to redeploy current (and figure out how to automate that as part of `npm publish`)...

**Comment by buschtoens** [comment]
> and figure out how to automate that as part of npm publish

[ember-cli-github-pages](https://github.com/poetic/ember-cli-github-pages) can do that.

**Comment by pzuraq** [comment]
I believe we have that setup, and I thought I had pushed the updated docs recently. Maybe I built but didn't push 😕

**Comment by buschtoens** [comment]
Looking at the [`release.js`](https://github.com/ember-decorators/ember-decorators/blob/master/config/release.js), it doesn't look like it. [ELT's `release.js`](https://github.com/offirgolan/ember-light-table/blob/master/config/release.js) for comparison.

**Comment by pzuraq** [comment]
Ah sorry, I meant we have ember-cli-github-pages installed. It's not automated as part of release, we should definitely add that!

**Comment by pzuraq** [comment]
This should be solved by the upcoming docs site, thanks for reporting this!
