### ISSUE TITLE
Impossible to install the addon 

### ISSUE THREAD

**Issue by Hugo-Contreras** [ember-decorators/ember-decorators#198]
Hi there,

I'm trying to install the addon and I get an error with on of the dependency.
`Install failed. Could not find addon with name: @ember-decorators/babel-transforms`

I'm using Ember CLI 2.12.3 with Node 6.12.0

**Comment by rwjblue** [comment]
You see that the package is published here: https://www.npmjs.com/package/@ember-decorators/babel-transforms

Its possible that your ember-cli version is older, and therefore is not able to load scoped addons...

**Comment by buschtoens** [comment]
I remember a time when `ember install` did not play nicely with scoped packages.

This https://github.com/ember-cli/ember-cli/pull/7109 is the only relevant PR I could find on the spot.

**Comment by Hugo-Contreras** [comment]
So I need to upgrade to Ember CLI 2.16 ? (at least)

**Comment by buschtoens** [comment]
If that is the PR that actually fixes it, yeah.

But if you're upgrading anyway, upgrade to the latest version right away.

**Comment by Hugo-Contreras** [comment]
Ok and what if I want to (have to) stay at Ember CLI 2.12.3 because of some other addons we are using which prohibe us to upgrade above 2.12.x ?

**Comment by buschtoens** [comment]
Then install the addons manually:

```
yarn add -D ember-decorators @ember-decorators/babel-transforms
```

or


```
npm i -D ember-decorators @ember-decorators/babel-transforms
```

I can only urge you to either get the addons fixed or remove them. Staying behind will only lead to problems in the long run.

**Comment by Hugo-Contreras** [comment]
Thank you for the help !

And yes I know we should have them upgraded but unfortunately it's not "under my watch" :(
