### ISSUE TITLE
Canary InjectedProperty issue

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-decorators/ember-decorators#199]
![image](https://user-images.githubusercontent.com/199018/36065304-c6efaaea-0e66-11e8-830e-ab2a9910b424.png)

![image](https://user-images.githubusercontent.com/199018/36065310-d009af04-0e66-11e8-8a69-231b77a62ca9.png)

'this':

![image](https://user-images.githubusercontent.com/199018/36065322-f83863f8-0e66-11e8-933b-eaf7036bde85.png)

**Comment by rwjblue** [comment]
Currently, decorators install computed properties to the prototype by "simply" setting up the right value on the specific field. Instead we should likely use `Ember.defineProperty` (which should work for new and older Ember versions)...

**Comment by pzuraq** [comment]
v2.0.0-beta.1 has been released and should fix these issues! Let me know if you have any problems, I'll close this issue once we get to v2.0.0 stable

**Comment by pzuraq** [comment]
Closing this issue for now
