### ISSUE TITLE
Using @service with ES Classes and TS seems to be breaking something

### ISSUE THREAD

**Issue by cptran777** [ember-decorators/ember-decorators#201]
Hey everyone,

It looks like I'm running into the following error when trying to inject a service into my route:

```
Uncaught TypeError: Cannot use 'in' operator to search for 'writable' in undefined
    at normalizeDescriptor (normalize-descriptor.js:26)
    at handleDescriptor (decorator-wrappers.js:14)
    at decorator-wrappers.js:45
```

This is my sample from my code:
```
import { service } from 'ember-decorators/service';

class MyRoute extends Route {
  @service('get-org-context') getOrgContext: any;
  ...
}
```

This will throw the above error. When I try using the following method:
```
import { service } from 'ember-decorators/service';

class MyRoute extends Route {
  @service getOrgContext: any;
  ...
}
```

No error gets thrown but `getOrgContext` ends up being `undefined` when trying to access it. Is this a bug or is there something wrong with my implementation method? Thanks!

**Comment by pzuraq** [comment]
TypeScript compatibility is known issue. We’re currently workinf on v2, which will support TS, stay tuned for a beta release later today!

**Comment by pzuraq** [comment]
v2.0.0-beta.1 has been released and should fix these issues! Let me know if you have any problems, I'll close this issue once we get to v2.0.0 stable

**Comment by kernel-io** [comment]
I'm having an issue with this also (I think), I just updated my app to 3.1 and ember-decorators v2.

I'm now getting a 'Error: Could not find module `ember-decorators/service` imported from `facebook-for-dogs/pods/components/dog/component`'

**Comment by pzuraq** [comment]
The import path has changed for v2, try importing from `@ember-decorators` instead
