### ISSUE TITLE
Feature request: positionalParams for components

### ISSUE THREAD

**Issue by jamesarosen** [ember-decorators/ember-decorators#208]
The following:
```js
export default MyComponent extends Component {
  static positionalParams = [ 'foo', 'bar' ]
}
```
compiles to
```js
// ...
MyComponent.positionalParams = [ 'foo', 'bar' ]
// ...
```
instead of
```js
.reopenClass({
  positionalParams: [ 'foo', 'bar' ]
})
```
I _suspect_ we need to instead have a `positionalParams` decorator that emits a `reopenClass`.

See also #123

**Comment by jamesarosen** [comment]
Aha!

`static positionalParams = [ 'foo', 'bar' ]` _does_ work. The problem was that I had
```js
class MyComponent extends Component {
  foo = ''
  bar = ''
}
```
and those initializations overrode what I was passing in as positional params.

**Comment by buschtoens** [comment]
You might also be interested the `@argument` decorator. ;)

**Comment by jamesarosen** [comment]
TIL: https://github.com/ember-decorators/argument 😃🎉
