### ISSUE TITLE
mutate descriptors don't create new descriptors.

### ISSUE THREAD

**Issue by stefanpenner** [ember-decorators/ember-decorators#21]

**Comment by pzuraq** [comment]
Would this just mean changing https://github.com/rwjblue/ember-computed-decorators/blob/master/addon/utils/decorator-wrappers.js#L3-L10

to

```

function handleDescriptor(target, key, desc, fn, params = []) {
  desc.value = fn(target, key, desc, params)
  return desc;
}
```

**Comment by rwjblue** [comment]
@pzuraq - Yes, I believe so.

**Comment by pzuraq** [comment]
This is pretty stale at this point, the system for creating/mutating descriptors has changed quite a bit. In general, with computed properties we actually use `Ember.defineProperty` directly so we get the correct descriptor (with ES5 getters setup and everything). Going to close this for now, feel free to reopen!
