### ISSUE TITLE
Consider refactoring back to a mono-repo

### ISSUE THREAD

**Issue by pzuraq** [ember-decorators/ember-decorators#212]
The overhead of maintaining this library has been growing as we've broken out the individual packages into their own git repositories. The separation of concerns by package does make sense, but we could probably benefit by moving back to a mono-repo that contains all of the separate packages/addons. We should consider using [lerna.js](https://lernajs.io/) to manage the packages.

**Comment by buschtoens** [comment]
Lerna seems like an industry standard by now. In favor of this! 

Do you want to keep packages like `babel-transforms` and `argument` in separate repos?

**Comment by pzuraq** [comment]
`babel-transforms` and `utils` should be brought into the mono-repo because they are very necessary for the library to function, and will probably continue to be. `argument` and `auto-computed` should probably remain in separate packages, as they aren't the "recommended path" yet. 

I think the main repo should represent the core decorators that we believe should eventually be added to Ember itself, much like `ember-native-dom-helpers`. `@argument` is useful but I don't think we can elevate it to that status, especially given Glimmer components (if/when they do happen) will probably be fundamentally different and require us to reconsider our basic model.

**Comment by chilicoder** [comment]
I totally support this proposal. Its too complex for such a small scope
