### ISSUE TITLE
@macro decorator/function

### ISSUE THREAD

**Issue by pzuraq** [ember-decorators/ember-decorators#213]
Currently there is no easily accessible way to make our own macro decorators. We should provide a function which takes existing computed macros (such as those in [ember-awesome-macros](https://github.com/kellyselden/ember-awesome-macros)) and converts them into decorators. The helper will be invokable directly and indirectly by binding to a different variable, e.g.

```js
let foo = macro(bar);

class Foo {
  @foo baz;
  @macro(bar) qux;
}
```

**Comment by buschtoens** [comment]
Happy to submit a PR, if you're not already working on it.
Where should I put this? Create it's own package, put in `@ember-decorators/utils`, add it to `/object/computed`?

**Comment by buschtoens** [comment]
Actually, there's a fourth style:

```js
let foo = bar('a', 'b');

class Foo {
  @macro baz = foo;
  @macro qux = bar('c', 'd');
}
```

**Comment by pzuraq** [comment]
I think this should be added to `@ember-decorators/object/computed` for now.

For the invocation styles, I think the first version is the best one aince it allows users to pretty easily created macros that they can then use as decorators:

```js
let myMacro = macro(foo);
```

The second style is interesting. Partial applications could be pretty useful, but I’m not sure it’s a major priority. If it’s easy enough to do, we can try it out.

**Comment by buschtoens** [comment]
The third and fourth suggested style actually have quite different semantics. They should be tracked in a different issue and their decorator should be called something like `@mountComputedProperty`.

```js
class Foo {
  @mountComputedProperty(foo('c', 'd')) bar;
}
```

```js
class Foo {
  @mountComputedProperty bar = foo('c', 'd');
}
```
