### ISSUE TITLE
@computed "Assertion Failed: ES6 property getters/setters only need to be decorated once"

### ISSUE THREAD

**Issue by gossi** [ember-decorators/ember-decorators#214]
As already mentioned in slack. @computed stopped working, after updating to ember@3.1 (from ember@3.0). 

- Test-Repo: https://github.com/gossi/ember-decorators-computed-test
- Relevant are the components `dialog-one`, `dialog-two`, `dialog-three`.
- They inherit from `DummyDialog` (which is present in my original app)-
- `DummyDialog` inherits from `FormDialog` in: https://github.com/athlyzer/ember-athlas-modal/blob/master/addon/components/form-dialog.js

**Comment by gossi** [comment]
As `@chilicoder` mentioned to try `@readOnly` above the `@computed` statements the error message turned into: `Assertion Failed: Attempted to apply @readOnly to a computed property that didn't have a setter, which is unnecessary`

**Comment by pzuraq** [comment]
Alright, got a chance to dig in, this is a bug in the way that we are reading computed property descriptors in the latest versions of Ember. I'll be able to push out a fix soon, just gotta figure out the right way to do it.

**Comment by pzuraq** [comment]
This should be fixed on `master`, trying to get the 2.1 release out soon!
