### ISSUE TITLE
Parsing error: Unexpected character '@' - Ember 3(?)

### ISSUE THREAD

**Issue by givanse** [ember-decorators/ember-decorators#223]
In `ember-cli: 3.0.4` I am seeing this error `Parsing error: Unexpected character '@'`.

After a google search, I started to follow this thread 

> [The Broccoli Plugin: [broccoli-persistent-filter:Babel] failed](https://github.com/ember-decorators/ember-decorators/issues/90)

It says that you needed to add the correct babel plugin. I tried to do that. Some time later I found I wasn't even required to do that anymore, since this PR deleted the docs and automated the process: https://github.com/ember-decorators/ember-decorators/pull/121

It wasn't working anyway, so I tried the old docs, but no dice.
[Add instructions for using Babel 6.x](https://github.com/ember-decorators/ember-decorators/pull/95)

So, either way I see the error.

```
8:1  error  Parsing error: Unexpected character '@'
```

Line 8 looks like this
```
@classNames('class-one', 'class-two')
class SomeComponent extends Component {
...
```

**Comment by buschtoens** [comment]
How did you install this addon?

```
ember install ember-decorators

```

Is `@ember-decorators/babel-transforms` in your `package.json`?

**Comment by givanse** [comment]
yeah `ember install ember-decorators` and the diff for my package.json shows

```
   "devDependencies": {
+    "@ember-decorators/babel-transforms": "^2.0.0",
+    "ember-decorators": "^2.0.0",
```

my import
```
import {
  action,
  computed,
  alias,
} from '@ember-decorators/object';
```

I'll try to setup a repro repo.

**Comment by givanse** [comment]
New ember app from scratch that reproduces the error:
https://github.com/givanse/decorators-unexpected-character

**Comment by pzuraq** [comment]
Ah, so that's not actually a _build_ error, that's a linting error. ESLint does not understand decorators yet, so it's failing to parse the file. Do `yarn add babel-eslint` and set `parser: 'babel-eslint'` in your eslint config and it should work. These steps will be added to the updated guides shortly!

**Comment by givanse** [comment]
Cool, that was it, thanks!
