### ISSUE TITLE
The doc link isn't working

### ISSUE THREAD

**Issue by abhishek97** [ember-decorators/ember-decorators#233]
The link to the docs is not working: https://ember-decorators.github.io/ember-decorators/docs/index.html

**Comment by pzuraq** [comment]
We’re aware of the issue, currently waiting to get access to GH settings so we can turn github pages back on

**Comment by pzuraq** [comment]
This has been resolved, you should be able to visit the docs site at https://ember-decorators.github.io/ember-decorators
