### ISSUE TITLE
route queryParams support

### ISSUE THREAD

**Issue by jamesarosen** [ember-decorators/ember-decorators#235]
If I do this in a route
```js
export default MyRoute extends Route {
  queryParams = { foo: { refreshModel: true } }
}
```
then calling `transitionTo(currentRoute, { queryParams: { foo: 'new-foo' } })` doesn't work. (In my tests, it seems to work on every other invocation, oddly.)

This works:
```js
export default MyRoute extends Route {
  init() {
    super.init(...arguments)
    this.set('queryParams', { foo: { refreshModel: true } })
  }
}
```

as does this:
```js
export default MyRoute extends Route {
  @computed // or without @computed
  get queryParams() {
    return { foo: { refreshModel: true } }
  }
}
```

This doesn't work:
```js
export default MyRoute extends Route {
  constructor() {
    super()
    this.set('queryParams', { foo: { refreshModel: true } })
  }
}
```
because `serializeQueryParam` throws a null-pointer exception [here](https://github.com/emberjs/ember.js/blob/v3.1.1/packages/ember-routing/lib/system/route.js#L428) trying to call `this._router._serializeQueryParam(value, defaultValueType);`

**Comment by jamesarosen** [comment]
Actually, none of those options work reliably. If I load `/my-route?foo=bar`, then call `transitionTo('my-route', { queryParams: { foo: 'baz' } })`, everything works as expected. But if Ember starts routing with no query-param (`/my-route`), the _first_ `transitionTo` doesn't set a query-param. Only subsequent ones do. This is true for the `init` and the `get queryParams` variants.

**Comment by pzuraq** [comment]
@jamesarosen I haven't been able to dig into this so far, but according to folks in the Typescript channel that I've talked to they've been able to use QPs by using class field assignment. I have a feeling the issues you're encountering may also be fixed by the changes proposed in [RFC 337](https://github.com/emberjs/rfcs/pull/337) as well.

Can you produce a test case or example of the failure?

**Comment by jamesarosen** [comment]
I suspect this is exactly what RFC 337 addresses.

**Comment by pzuraq** [comment]
This has been addressed in RFC337, the implementation of which has been merged and should be released soon
