### ISSUE TITLE
[Typings] hasMany and belongsTo parameters

### ISSUE THREAD

**Issue by gossi** [ember-decorators/ember-decorators#239]
Both relationship decorators miss the typings, where they accept only one argument (the options).

Dunno what's the best here, either have three overload methods typed or one, that takes an optional `options` parameter, something like this:

```
export function belongsTo(options?: DS.RelationshipOptions): PropertyDecorator;
```

I have no idea whether my typings are correct here.

**Comment by pzuraq** [comment]
I believe this has been fixed, let me know if you're still having issues! We have TS tests now, so we can test all types of configurations
