### ISSUE TITLE
The @argument decorator doesn't work with Ember 3.1's named args feature

### ISSUE THREAD

**Issue by lsg-richard** [ember-decorators/ember-decorators#241]
It appears that it's not currently possible to use the default argument value feature of `@ember-decorators/argument` together with the named args feature in Ember 3.1.

Take the following component JavaScript and template:

```js
export default class MyComponent extends Component {
  @argument test = 'test-value'
}
```

```hbs
Value of test is: {{test}}
Value of @test is: {{@test}}
```

Invoking it with no arguments gives the following:

```
Value of test is: test-value
Value of @test is:
```

I was expecting `@test` to evaluate to `test-value`, not be undefined. If the `test` argument is given a value on invocation, i.e. `{{my-component test='abc'}}` then everything works fine.

Are default values specified when using `@argument` intended to work with named args?

Thanks.

**Comment by buschtoens** [comment]
Relevant links:

- https://glimmerjs.com/guides/templates-and-helpers
- https://github.com/emberjs/rfcs/blob/master/text/0276-named-args.md

It's not mentioned explicitly in the RFC, but I _guess_ the correct way to access `@foo` in JS land is via `this.args.foo`, right?

**Comment by dfreeman** [comment]
Will `Ember.Component` ever have `this.args` or some equivalent way to access named args from JS? It seems unfortunate that the way a component is using some input has an impact on how it can be invoked.

If I start writing a simple component `{{my-component @name='hello'}}` today, and down the line wind up wanting to have some piece of derived state in that component that depends on `name`, I then have to update every use of that component to switch the named arg to a regular property.

To me that feels like an implementation detail leaking out to the consumer—am I thinking about this wrong? 🤔

**Comment by pzuraq** [comment]
I think this is where Glimmer Components ™️ come in no? They’ll be splatting attributes onto top level atrributes of template, and adding args to the `args` hash on components

**Comment by dfreeman** [comment]
Right, Glimmer Components have nice interop with named args, but we don't have access to those in Ember apps yet. I'm curious about whether it ever actually makes sense to use named args in the world as it exists today with `Ember.Component` — is that ever _not_ a refactoring hazard?

**Comment by rwjblue** [comment]
> Will Ember.Component ever have this.args or some equivalent way to access named args from JS? It seems unfortunate that the way a component is using some input has an impact on how it can be invoked.

I think its likely that we will try to advance glimmer components (which does include `this.args` support) before making any significant changes to `Ember.Component`. However, I _do_ think considering a bridging path between the two to make migration/interop easier (e.g. adding `this.args`).

> If I start writing a simple component {{my-component @name='hello'}} today

Minor correction first: invocation syntax for curly components does not change, and would still be `{{my-component name='hello'}}`.

> and down the line wind up wanting to have some piece of derived state in that component that depends on name, I then have to update every use of that component to switch the named arg to a regular property.

OK, now into the meat of this part. I realize the hypothetical here seems to paint an annoying future, but to be honest, I think its a great way to talk about the various workflows in play. 

In this scenario you have a template that starts out to simply pass through an original input value, then you decide that the component needs to mutate that value (disconnecting it from its input, changing its meaning perhaps, etc). It seems to me that having a sigil in the template to make that crystal clear is a good thing, not a refactoring hazard. Changing the underlying value _should have_ forced you to evaluate all the other template references, to confirm that you haven't caused another issue for yourself.

In this hypothetical, if the original template had used named arguments for the pass through value any readers at that time would clearly have understood that they need not look at the component's JS file to understand what the value is (and that it is a straight pass through value). Then after the refactor was done, they see the non-named argument usage and know that they need to read the component JS file to understand what is going on.

> Right, Glimmer Components have nice interop with named args, but we don't have access to those in Ember apps yet. I'm curious about whether it ever actually makes sense to use named args in the world as it exists today with Ember.Component — is that ever not a refactoring hazard?

I don't think the value proposition of named args changes with glimmer components at all. Perhaps you were thinking that you could mutate `this.args`?

Also, don't forget the (quite important) usage of template only components...

**Comment by dfreeman** [comment]
> Minor correction first: invocation syntax for curly components does not change, and would still be `{{my-component name='hello'}}`.

😳 That was the crux of my confusion - I'm totally on board with having a sigil in the template _using_ the value to indicate it's consuming something that's passed directly through. I just reread the named args RFC and realized I'd been inferring something that's not there at all: the `@` on the component invocation side.

My entire (misplaced) apprehension was that changing the internals of the component could force consumers of that component to have to switch from `{{my-component @name='hello'}}` to `{{my-component name='hello'}}`, but since the former isn't actually a thing, I was just spouting nonsense. Sorry about that!

> I don't think the value proposition of named args changes with glimmer components at all. Perhaps you were thinking that you could mutate this.args?
> Also, don't forget the (quite important) usage of template only components...

💯 For sure. This was all just the same confusion about invocation as above-definitely not wanting to mutate `args` or discounting template-only components.

**Comment by dfreeman** [comment]
Thanks for the explainer! Honestly I think I just didn't read either of those RFCs closely enough and assumed some things that were just patently false—the world makes a lot more cohesive sense now 😄

**Comment by lsg-richard** [comment]
Interesting discussion!

I agree that given named args are defined as being exactly what was passed in by the caller, and are immutable, that the behavior here makes sense. My initial expectation of defaulting being available on named args probably came from the fact that they're both referred to as args/arguments. The term "named args" always struck me as odd, because haven't component arguments always had names, even before Ember 3.1? Though given that they're all just splatted onto the component class, you didn't actually know where a value originated, but now you can make that explicit.

I think that not having defaulting available on named args makes them less useful - being able to easily default a boolean arg to true is quite handy. Is there a middle ground here? How does Glimmer handle having defaults on args?

To avoid sometimes using named args and sometimes not depending on whether a default was needed, my team will likely just avoid them until adopting Glimmer components forces us to be aware of the distinction.

**Comment by pzuraq** [comment]
Closing this issue for now based on the discussion, sounds like everything is working as it should be and this is mostly just a bit of pain from new behaviors as we move toward Glimmer components.

**Comment by lougreenwood** [comment]
I just stumbled across this issue and I have one thing to add:

> Then after the refactor was done, they see the non-named argument usage and know that they need to read the component JS file to understand what is going on.

Isn't this contrary to the spirit of the RFC (https://github.com/emberjs/rfcs/blob/master/text/0276-named-args.md)?

> The first problem with this approach is that the {{name}} syntax is highly ambigious, as it could be referring to a local variable (block param), a helper or a named argument from the caller (which actually works by accessing auto-reflected {{this.name}}) or a property on the component class (such as a computed property).

When I see `{{foo}}` in a template, how am I supposed to know whether this means:

* developer who created component wasn't aware of named args and used `{{foo}}` even though they reference externally passed args?
* code was created before named args, but references externally passed arg (essentially the same as above, but I can't blame someone else 😄)
* `{{foo}}` actually means use default value in template OR passed arg (@rwjblue 's suggestion)
* any of the other ambiguities this RFC aims to avoid (is it a helper, is it a plane etc)?

I'm still confused how to properly handle default values for named args in a nice, clean way :(

**Comment by pzuraq** [comment]
@lougreenwood I think it may be easier to consider what the future looks like with Sparkles/Glimmer components style API for all args. In the future, instead of having arguments assigned to the class instance, they will _only_ be available on `this.args`, as an object. Defaults will not be directly assignable, so it’ll be very clear when something is an arg directly passed in, or it has gone through some kind of processing.

**Comment by lougreenwood** [comment]
@pzuraq thanks, do you know of any RFCs or anything where I can read more about this? It sounds a bit confusing :)

**Comment by pzuraq** [comment]
You can check out the current implementation of sparkles components here: https://github.com/rwjblue/sparkles-component

This has the args API I’m talking about, so it should be able to give you an idea of how that would work.
