### ISSUE TITLE
Install sets parser to babel-eslint regardless of if it was the default setting or overridden

### ISSUE THREAD

**Issue by localpcguy** [ember-decorators/ember-decorators#244]
I have `ember-cli-typescript` installed and am using the `parser: 'typescript-eslint-parser'`, but upon installing Ember-Decorators it was set to `parser: 'babel-eslint'`

Expected: 
If the parser is not the default parser for ESLint, do not override with `babel-eslint` 

Optionally: 
Raise a warning stating that Ember Decorators didn't change the parser due to it already being overridden

re: [Link to afterInstall script](https://github.com/ember-decorators/ember-decorators/blob/master/packages/-ember-decorators/blueprints/ember-decorators/index.js#L44-L54)

**Comment by buschtoens** [comment]
Sorry for the tangent, but out of curiosity, since I haven't seen this thing before:
 
- Are you using eslint to lint your js files?
- Does it work well?
- Are there TS specific rules?
- Is it better than tslint?
- Are you using both?

**Comment by localpcguy** [comment]
Yes, ESLint for both JS and TS files. To set it up for that, I am using [typescript-eslint-parser](https://github.com/eslint/typescript-eslint-parser) as the parser. For rules, I also installed [eslint-plugin-typescript](https://github.com/nzakas/eslint-plugin-typescript) although I have most of those rules turned off right now since it's still early days using Typescript for us.

I am not using TSLint - didn't want to introduce another linter since it seems (so far) like ESLint will accomplish what we need for both JS and TS files.

**Comment by dfreeman** [comment]
The main thing TSLint has going for it is that it can have type-aware rules. ESLint only operates at a syntactic level, so even with the TypeScript plugin, it can't enforce rules that rely on understanding the semantics of your code.

That said, TSLint is super opinionated out of the box with a lot of stylistic rules, and I've generally found that the rules I care about can either be enforced by ESLint or by the TS compiler itself, so like @localpcguy I've erred on the side of keeping it simple in my TS projects and just using ESLint.
