### ISSUE TITLE
Make @macro work without `computed`

### ISSUE THREAD

**Issue by buschtoens** [ember-decorators/ember-decorators#248]
Currently there is no easy way to "mount" an instance of a `ComputedProperty` on a class. For lack of a better name, I'll use the name `@mountComputed` here.

```js
import EmberObject, { computed } from '@ember/object';
import { mountComputed } from '@ember-decorators/object/computed'; // or just /object ?

const fullNameGenerator = computed('firstName', 'lastName', function() {
  return `${this.firstName} ${this.lastName}`;
});

class Person extends EmberObject {
  firstName = 'Alan';
  lastName = 'Turing';

  // computed property as value
  @mountComputed fullName = fullNameGenerator;

  // computed property as argument
  @mountComputed(fullNameGenerator) fullName;
}
```

- Do we need / want this decorator?
- What do we want to call it?
- Which invocation style do we prefer? Or do we want to allow both in parallel?

**Comment by pzuraq** [comment]
I don't think this is a good idea, eventually non-decorator `computed`s should probably not be a thing. Though, we should have a decorator that is essentially `@macro` but doesn't require users to return a computed, somehow. Essentially, it should be possible to write a macro without having to use `computed` directly.

**Comment by pzuraq** [comment]
Yeah, I think this is going to be tricky no matter what, at least until `@tracked` becomes a thing with autotracking.

I think we could possibly add the dependent keys to the return value, which would allow the macro to figure it out:

```js
import { computed } from '@ember/object';
import { macro } from '@ember-decorators/object/computed';

const greeter = macro((greeting, firstNameKey, lastNameKey) =>
  return {
    dependentKeys: [firstNameKey, lastNameKey],
    
    get() {
      return `${greeting} ${this[firstNameKey]} ${this[lastNameKey]}`;
  	}
  }
);

class Person extends EmberObject {
  firstName = 'Alan';
  lastName = 'Turing';

  @greeting('Good morning', 'firstName', 'lastName') greeting; // => 'Good morning Alan Turing' 
}
```

**Comment by krisselden** [comment]
there is always the workaround of just calling Ember.defineProperty() on the MyClass.prototype and if using typescript, declaring the property.

**Comment by pzuraq** [comment]
This is more about how we allow users to define macros in a world with only decorators. The current `@macro` decorator is a bit clumsy, because it requires the user to use the pre-decorator `computed` function which could get very confusing. It does however call `Ember.defineProperty` under the hood, so computed properties are getting mounted properly. I think we should rename the issue to make it a bit clearer.

**Comment by buschtoens** [comment]
Cross-posting from Slack: I had a bit of trouble using `@macro` with ember-awesome-macros. Intuitively I wanted to do this:

```ts
@macro(bool(or('title', 'clickAdd'))) hasHeading!: boolean;
```

Which didn't work. And it makes sense, if you think about it: `@macro` expects a function that creates a computed property that it then can slap onto the instance.

So you need to do either this:

```ts
@macro(bool, or('title', 'clickAdd')) hasHeading!: boolean;
```

Or my personal preference:

```ts
@macro(() => bool(or('title', 'clickAdd')) hasHeading!: boolean;
```

ember-awesome-macros still uses `computed` under the hood, but this is the original problem I alluded to in my opening post. The code from above could be rewritten as:

```ts
import EmberObject, { computed, get } from '@ember/object';
import { macro } from '@ember-decorators/object/computed';

const fullNameGenerator = computed('firstName', 'lastName', function() {
  return `${get(this, 'firstName')} ${get(this, 'lastName')}`;
});

class Person extends EmberObject {
  firstName = 'Alan';
  lastName = 'Turing';

  @macro(() => fullNameGenerator) fullName;
}
```

**Comment by pzuraq** [comment]
I think the ideal way to use `macro` currently is to shim existing macros, rather than using it as a decorator directly. This is also much more codemoddable:

```js
const bool = macro(boolComputed); 

class Person extends EmberObject {
  @bool(or('title', 'clickAdd')) hasHeading!: boolean;
}
```

This is the way I see us transitioning existing macro functions, until the ecosystem rewrites them to use decorators directly (hopefully with the extra functionality I outlined above)

**Comment by pzuraq** [comment]
Note, I don't think we should necessarily add this to `ember-decorators` just yet, not sure how many use cases there are for nestable decorators. I also think there are other, potentially more efficient ways to do this. Mostly pointing out that I think there are better solutions to the mounting computeds problem.

**Comment by pzuraq** [comment]
Closing this as `macro` has been removed from the library
