### ISSUE TITLE
className decorator not effective until after initial render

### ISSUE THREAD

**Issue by ezpuzz** [ember-decorators/ember-decorators#253]
The following does not work properly for me
```
  @className('active', 'inactive') isActive = true;
```
Ember 3.3.0
ember-angle-bracket-invocation-polyfill

I render a component like
```javascript
{{#each model.children as |c|}}
<MyComponent @model={{c}} @isActive={{c.isSomething}} />
{{/each}}
```

and MyComponent is like

```
{{model.isSomething}}
```

The component only gets the `active` class even though `isSomething` is true for half the children and false for the rest.  If I add a child to model.children then the classes update and display as intended.

Using `classNameBindings = ["isActive:active:inactive"]` works as intended immediately.

**Comment by pzuraq** [comment]
Which version of `ember-decorators` are you using?

**Comment by ezpuzz** [comment]
2.2.0

**Comment by pzuraq** [comment]
So one thing that is interesting here is that this probably shouldn't be working at all. Class fields will always overwrite argument values, so you need to check if the field is assigned before assigning a default:

```js
@className('active', 'inactive') isActive = this.isActive !== undefined ? this.isActive : true;
```

Subsequent updates will overwrite the value in both cases, so maybe this is your issue? You can find more info in the [class fields section of the docs](https://ember-decorators.github.io/ember-decorators/latest/docs/class-fields)

**Comment by ezpuzz** [comment]
ah, I see, yes that fixes the behavior to match `classNameBindings`.  Annoying that this this decorator requires more verbosity than existing `classNameBindings` for the same behavior.

Leaving without a default value defaults it to falsey, assigning a default value ignores the argument until it changes/computes.

Also the `@argument` decorator works to restore `classNameBindings` behavior.

**Comment by pzuraq** [comment]
This is more related to the behavior of class field in general than the `@className` decorator. The [Native Class Constructor Update RFC](https://github.com/emberjs/rfcs/pull/337) would address this issue, but otherwise all arguments have to have some defaulting logic

**Comment by ezpuzz** [comment]
ah cool, I'll follow that discussion.  Thanks for all your work, I will close this.
