### ISSUE TITLE
Add TS typings for @macro

### ISSUE THREAD

**Issue by pzuraq** [ember-decorators/ember-decorators#257]

**Comment by buschtoens** [comment]
Closed via https://github.com/ember-decorators/ember-decorators/pull/258.

Do you want to keep this open as a reminder for TypeScript 3 supporting variadic args?

**Comment by pzuraq** [comment]
I think that'd be a good idea, we should update as soon as TS is available

**Comment by buschtoens** [comment]
Updating these types would break compatibility with TS 2.x. Is there a way to ship different types for different TS versions?

**Comment by mike-north** [comment]
> Is there a way to ship different types for different TS versions?

There's a way (npm dist tags) but I wouldn't advise it.

<img width="805" alt="screen shot 2018-12-17 at 5 46 18 pm" src="https://user-images.githubusercontent.com/558005/50126916-c42e7280-0223-11e9-91ac-ac4e9f8a00b7.png">

**Comment by pzuraq** [comment]
Yeah I think if that's the case we should punt on this. If the decorators RFC is merged, we'll be deprecating and removing `@macro` anyways, so I think it's better.

**Comment by pzuraq** [comment]
Closing this issue, `macro` will be removed in the next major version of `ember-decorators`
