### ISSUE TITLE
duplicate plugin/preset detected

### ISSUE THREAD

**Issue by nightire** [ember-decorators/ember-decorators#274]
Prior declaration: I can't confirm whether this bug was caused by ember-decorators or not, and I've post a similar question in [ember-cli slack channel][1] (no responses however).

How did this bug happened:

1. create a new add-on, install a bunch of add-ons, include `ember-decorators`, everything is up to the latest stable version.

2. install one of my add-on, to provide some common utilities, this add-on doesn't use `ember-decorators`, but other dependencies are all up to the latest stable version

3. boot up ember server, error happened:

```
Build Error (broccoli-persistent-filter:Babel > [Babel: @choiceform/ui-foundation]) in @choiceform/ui-foundation/helpers/icon.js

Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Stack Trace and Error Report: /var/folders/9_/y4f4n_cd5ddbzftt3x0rz19w0000gn/T/error.dump.a3ef75fbf5ceac6af9132220a7587e6e.log
```
(`@choiceform/ui-foundation` is the utility add-on mentioned in list item 2)

I put a debugger where threw the exception, then noticed it was caused by the repeated definition of these two plugins:

1. `babel-plugin-transform-decorators-legacy`
2. `babel-plugin-transform-class-properties`

turns out this line was been invoked twice in my case:

https://github.com/ember-decorators/babel-transforms/blob/76d2a0624cc911d27cea3d4f19aa1f32efcb452e/index.js#L20

so `setupBabel` pushes the same set of plugins twice as well.

Buy why? My best guess is nested add-ons, but I don't want to speculate too much to avoid misleading.

[1]: https://embercommunity.slack.com/archives/C045BNHAP/p1535626744000100

**Comment by nightire** [comment]
I just realized the `ember-cli-babel` in the new add-on is still on version `v6.x`, but after I upgrade it to `v7.1.0`, a new error happened:

```
Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
```

It forces me to remove those add-ons who depends on `babel-core@6.x`:

- `ember-auto-import`
- `ember-concurrency`
- `ember-fetch`

now it is back to the original error...I have to say, upgrade to `babel@7` is really a pain point currently.

**Comment by nightire** [comment]
Actually there is a bug in my own code, in the nested add-on I wrote:

```
this.options = defaultsDeep(parent.options, this.options);
```

what I really want is actually:

```
this.options = defaultsDeep({}, parent.options, this.options);
```

this simple change fixes my case.

**Comment by pzuraq** [comment]
Closing because it seems like you worked this out, feel free to reopen if needed
