### ISSUE TITLE
Attribute Decorator does not work as argument only

### ISSUE THREAD

**Issue by spencer516** [ember-decorators/ember-decorators#276]
When creating a component that sets an attribute based on a passed in property, the attribute is never set in the rendered element. 

Given this component: 

```js
// app/components/my-component.js
export default class extends Component {
  @attribute('data-value')
  value;
}
```

And invoked as:

```hbs
<MyComponent @value="1234">
{{! -- OR --}}
{{my-component value="1234"}}
```

I would expect the HTML that gets rendered to be:

```html
<div data-value="1234"></div>
```

However, the element that gets rendered does not have the attribute added to it. 

There are a couple of workarounds at the moment:

1. Add a property initializer that sets the value to itself:

```js
// app/components/my-component.js
export default class extends Component {
  @attribute('data-value')
  value = this.value;
}
```

2. Use the `alias` computed decorator and name the attribute property something else:

```js
// app/components/my-component.js
export default class extends Component {
  @attribute('data-value')
  @alias('value')
  someValue;
}
```

**Comment by pzuraq** [comment]
This issue is a core issue in Ember, which will be fixed by the recently merged [class constructor update RFC](https://github.com/emberjs/rfcs/blob/master/text/0337-native-class-constructor-update.md). We can keep this issue open until we get the fix out there

**Comment by pzuraq** [comment]
The class constructor update has been merged and should be available soon, we're going to begin working on polyfill backports in the near future as well.

**Comment by spencer516** [comment]
Fah-bew-luss — Thanks @pzuraq!

![ojbr914lliete](https://user-images.githubusercontent.com/2889608/46366634-95075c80-c649-11e8-9595-47791bd9e779.gif)

**Comment by pzuraq** [comment]
Any time! 😄
