### ISSUE TITLE
Support for Stage 2 decorators

### ISSUE THREAD

**Issue by buschtoens** [ember-decorators/ember-decorators#278]
Babel 7.1 with stage 2 decorator support is out:

- https://babeljs.io/blog/2018/09/17/7.1.0
- https://babeljs.io/blog/2018/09/17/decorators

> The third important change introduced by the new proposal is about the arguments passed to the decorator functions.
>
> In the first version of the proposal, class elements decorators received a target class (or object), a key, and a property descriptor — similar in shape to what you would pass to Object.defineProperty. Class decorators took as their only argument a target constructor.
>
> The new decorators proposal is much more powerful: element decorators take an object which, other than changing the property descriptor, allows changing the key, the placement (static, prototype or own), and the kind (field or method) of the element. They can also create additional properties and define a function (a finisher) which is run on the decorated class.
>
> Class decorators take an object which contains the descriptors of every single class element, making it possible to modify them before creating the class.

Further discussion on Discord:

@pzuraq
> Unfortunately, don’t think we can switch until we have a story for TS users :disappointed:

@rwjblue
> I was thinking that we would do a thing conditionally?
>
> what I mean is that the consumer API seems fine/stable (with a few exceptions)
we would need to make our implementation handle all three ways (babel legacy, babel stage 2, and TS)
> which may be impossible?

@pzuraq
> @rwjblue I'm just not sure it'd be worth the effort vs waiting. The implementations are very different, it's going to be a complete rewrite
>
> we could have a build flag that switches between both codebases, I don't think it would be ideal to ship both or to keep them intermingled
>
>the only reason I think we would want to update now is to get a jump on the `export @dec class` change that is coming, unless that changes on the way to stage 3
>
> I'd definitely be down to start a stage-2 branch at the least though, so we can work out implementation details

**Comment by pzuraq** [comment]
Thanks for capturing this @buschtoens!

Another thing to note is that the ember-cli-typescript team is pushing for using Babel to compile TS rather than TS directly. If/when this switch happens, we'll be using a single transform version for decorators, so we'll be able to switch seamlessly for all users.

cc @dfreeman

**Comment by pzuraq** [comment]
This has been added in v3.1
