### ISSUE TITLE
Could not find module `ember-compatibility-helpers` imported from `@ember-decorators/argument/-debug/utils/validation-decorator`

### ISSUE THREAD

**Issue by mhluska** [ember-decorators/ember-decorators#285]
I've been seeing this error in the console after a mass update of versions after upgrading to Node 10. The only dependency I have that uses ember-decorators is [ember-attacher](https://github.com/kybishop/ember-attacher).

My versions:

ember-decorators 2.5.1
ember-compatibility-helpers 1.1.0
ember-attacher 0.13.7
ember-popper 0.9.1
ember-cli 3.4.3
ember-data 3.0.2
node v10.110

**Comment by nickschot** [comment]
I'm seeing the same thing. Also have the same ember-popper version (through ember-bootstrap) as the only dep using ember-decorators. I do also see ember-data 3.4.2 depending on @ember/ordered-set@2.0.1 which has an older version of ember-compatibility-helpers (1.0.2).

**Comment by mhluska** [comment]
@nickschot I have a PR to remove the decorators from ember-popper: https://github.com/kybishop/ember-popper/pull/94

**Comment by pzuraq** [comment]
The issue is unrelated to decorators directly, but a dependency of decorators. We're working on the fix, will have it available soon.

**Comment by pzuraq** [comment]
This issue should be fixed in the latest version of `ember-compatibility-helpers`, sorry about that!

**Comment by nickschot** [comment]
It is! Thank you @pzuraq
