### ISSUE TITLE
TypeError: (0 , _object.observes) is not a function

### ISSUE THREAD

**Issue by lougreenwood** [ember-decorators/ember-decorators#296]
When attempting to use the `observes` decorator, I get this error:

```
Uncaught TypeError: (0 , _object.observes) is not a function
    at Module.callback (VM14870 prog.js:13227)
    at Module.exports (VM14868 vendor.js:111)
    at requireModule (VM14868 vendor.js:32)
    at Class._extractDefaultExport (VM14868 vendor.js:162938)
    at Class.resolveOther (VM14868 vendor.js:162639)
    at Class.resolve (VM14868 vendor.js:162697)
    at _resolve (VM14868 vendor.js:34342)
    at Registry.resolve (VM14868 vendor.js:34092)
    at Registry.resolve (VM14868 vendor.js:34096)
    at _factoryFor (VM14868 vendor.js:33753)
```

Version info:
```
ember-decorators: 3.0.1
ember: 3.5.1
ember-cli: 3.5.0
node: 10.13.0
os: darwin x64
```

**Comment by pzuraq** [comment]
Can you paste the import path you’re using?

**Comment by lougreenwood** [comment]
`import { action, observes } from "@ember-decorators/object";`

**Comment by pzuraq** [comment]
Hmm, could be that another dependency of yours uses an older version of `ember-decorators`. This is a known issue with ember-cli, in this situation the last version of an addon that gets written to a build tree wins, and that’s not a predictable process.

You can generally check `yarn.lock` or the NPM lockfile to verify this. It should have multiple entries of the `ember-decorators` addon, and you can see what is requiring them. Then we can work to fix it upstream.

**Comment by lougreenwood** [comment]
Looks like it's these addons:

* ember-concurrency-decorators
* ember-steps
* ember-css-modules

I'll go ahead and create some PRs to update them - thanks for the tip!

**Comment by buschtoens** [comment]
I can highly recommend installing [ember-cli-dependency-lint](https://github.com/salsify/ember-cli-dependency-lint), which warns you about exactly this kind of problem 😊

**Comment by lougreenwood** [comment]
nice!!
