### ISSUE TITLE
@readOnly should also be a PropertyDecorator

### ISSUE THREAD

**Issue by HodofHod** [ember-decorators/ember-decorators#297]
Right now (v3), the `@ember-decorators/object/readOnly` decorator is typed as a `MethodDecorator` because of its usage with `@computed()` getters. But `@readOnly` can also be used on properties, like so:

```ts
@readOnly
@or('_foo', '_bar')
readonly foo!: string;
```

Typescript should not show an error for this usage, which is supported and actually works.

**Comment by HodofHod** [comment]
I imagine that `@volatile` will need the same change?

Also, it seems that using `MethodDecorator | PropertyDecorator` doesn't work, though `MethodDecorator & PropertyDecorator` does. 

@pzuraq  If that's an acceptable solution, I can make a PR with that change, plus add another example to the `@readOnly` and `@volatile` descriptions.

**Comment by pzuraq** [comment]
Yes, they'll both need this change, and sounds good, makes sense that it would be the intersection type.

**Comment by HodofHod** [comment]
Ok. I did the fix, but then noticed that the examples for `readOnly` and `volatile` are using what I assume is an older usage of `@computed`, before getters. I corrected that as well,
