### ISSUE TITLE
Updating to v3.1.0 gets an addon.name is not a function

### ISSUE THREAD

**Issue by Gorzas** [ember-decorators/ember-decorators#310]
I've just updated the library on my project and when I try to build the project I get this error:

``` 
addon.name is not a function
```
After some debugging I've found that it's this [line](https://github.com/ember-decorators/ember-decorators/blob/master/packages/utils/index.js#L58) that breaks the compilation and it doesn't let me to get the trace I needed (it was asking me to upgrade the library `ember-concurrency-decorators`).

Is it possible that some old addons had a different interface to getting their names? Anyway, I'm going to solve the problem and send a PR :smile:.

**Comment by rwjblue** [comment]
> Is it possible that some old addons had a different interface to getting their names?

No, not really. The issue most commonly is that `Project.prototype.name` is a function and that `Addon.prototype.name` is a string, this discrepancy has existed for a very long time.
