### ISSUE TITLE
Using ember-cli-typescript in an in-repo addon / engine causes compilation to fail.

### ISSUE THREAD

**Issue by kylenathan** [ember-decorators/ember-decorators#325]
Fails with the error:
```
Cannot read property '0' of null
```

The ember-cli-typescript version check doesn't allow for the "*" version typically used in engines.

https://github.com/ember-decorators/ember-decorators/blob/master/packages/utils/index.js#L75

**Comment by pzuraq** [comment]
Closing this because I _believe_ it was solved by #330, let me know if you still have this issue!
