### ISSUE TITLE
Components class fields cannot be overwritten

### ISSUE THREAD

**Issue by toovy** [ember-decorators/ember-decorators#332]
The docs states that it is possible to overwrite default class fields (at the bottom of the page) https://ember-decorators.github.io/ember-decorators/docs/class-fields

> Until recently, class field initializers would run after create parameters were assigned to the class. This meant that it was impossible to override the "default" values assigned in the class definition. This has since changed, and class fields will now always be assigned before create parameters, working as expected.

Personally I feel that this happens still in my codebase. Even if pass the multiple property in the template as true, it is always false (please see example below). 

I've upgraded to decorators@3.1.4 and ember-source@3.5.1. I'm using ember-cli-typescript@1.5.0. As ember-decorators/@argument does not work with typescript I'm not sure what I'm doing wrong or if I'm missing out a decorator.

```
{{my-component multiple=true}}
```

```
import Component from "@ember/component";

export default class MyComponent extends Component {

  // am I missing a decorator??
  public multiple: boolean = false;

}
```

Any help is appreciated.
Thanks. Kind regards,
Tobias

**Comment by pzuraq** [comment]
Hey @toovy! Sorry about the confusion here, the reason it's not working is that this behavior does not ship until Ember _3.6_. This is the version that native class support is officially stabilized in Ember, however there is a polyfill that supports v3.4 and v3.5: https://github.com/pzuraq/ember-native-class-polyfill

**Comment by toovy** [comment]
@pzuraq thanks for the clarification, will install the polyfill in the meantime!

**Comment by pzuraq** [comment]
Ember 3.6 has shipped now, going to close this issue

**Comment by toovy** [comment]
@pzuraq thanks, I can confirm that both solutions, either upgrading to ember 3.6 or installing the polyfill for 3.4 and 3.5 works!
