### ISSUE TITLE
Vscode suggests wrong import path

### ISSUE THREAD

**Issue by akatz** [ember-decorators/ember-decorators#342]
Using the vscode suggestion feature ( or auto imports ) results in imports from the wrong path. For example:
`import { action } from "@ember-decorators/object/published-types";`
should be:
`import { action } from "@ember-decorators/object";`

![screen shot 2018-12-15 at 2 47 59 pm](https://user-images.githubusercontent.com/817/50048099-8b9e6580-0078-11e9-9a4f-5de7564d64ff.png)

**Comment by buschtoens** [comment]
@mike-north Unless there is a clever trick, I don't know about, I suggest we use a `prepublishOnly` script to move the `.d.ts` files one level up.

**Comment by nightire** [comment]
btw, it used to be correct, so what we did recently to mislead the vscode?

**Comment by buschtoens** [comment]
The type declarations are hand written, because Ember Decorators itself does not use TypeScript yet. #320 has moved these type declaration files into the `published-types` sub-directory in order to test them.

**Comment by buschtoens** [comment]
I've gone ahead and merged #343, because I was able to verify it's functionality. AFAIK there is no way to tell TypeScript to use a different path for declarations. If any TS whiz does know a way to do this that is cleaner than moving the declarations before publishing, I am happy to implement it!
