### ISSUE TITLE
Not compatible with ember 3.4.4?

### ISSUE THREAD

**Issue by toranb** [ember-decorators/ember-decorators#347]
I installed a new version of ember-cli@3.4.4 and installed ember decorators using `ember install` but I seem to have found an incompatibility of some kind.

Using "ember-cli-babel": "^6.18.0" and "@ember-decorators/babel-transforms": "^3.1.5" along with "babel-eslint": "^8.2.6" and "ember-decorators": "^3.1.5"

I get the following compilation error

![broken](https://user-images.githubusercontent.com/147411/50540587-f9a75a00-0b59-11e9-85d2-6504c9cb9d02.png)

Here is the broken example project with 2 components (1 using es2015 class syntax)

https://github.com/toranb/example-ember-three-four-app

**Comment by toranb** [comment]
For reference I flipped this same project over to the stage 1 transform and ... it works :)

https://github.com/toranb/example-ember-three-four-app/commit/26204c8c5466609edbe8926c053bc95a0a31b329

**Comment by pzuraq** [comment]
As the warning states, v3.1.5 of the transforms does not support babel 6. The stage 2 transforms were never released for babel 6, so there is no way for us to support them. If you need to continue using babel 6, you can continue using an older version of the transforms.

**Comment by toranb** [comment]
Good to know! Thanks for babysitting me over the holiday dude :)

I honestly didn’t need this for anything so I’ll note what I’ve learned and move on with the day! Thanks for the quick reply!
