### ISSUE TITLE
`@on`: listening for events on foreign objects

### ISSUE THREAD

**Issue by buschtoens** [ember-decorators/ember-decorators#377]
https://github.com/ember-decorators/ember-decorators/blob/304eed16b94a7a61491b59a306376ff77e5f6e8d/packages/object/addon/index.js#L209-L243

I would have intuitively expected the `@on` decorator to clean up after itself in `willDestroy` and not leak event listeners. This is kind of an `ember-lifeline`-y thing.

**Comment by buschtoens** [comment]
Ah, this has not been an issue yet since path expressions are not allowed. It would be super handy, if you could do something like:

```ts
class {
  @service eventBus;

  @on('eventBus.fooEvent')
  onFooEvent() {
    // ..
  }
}
```

**Comment by pzuraq** [comment]
I’d like to match the Ember APIs directly in this library. If `Ember.on` doesn’t support chains, I don’t think we should. There are going to be some internal refactors for observers and listeners soon too, definitely eant to make sure we’re not straying too far

**Comment by buschtoens** [comment]
👍 on staying as close as possible and effectively making this package a polyfill for the RFC.

However, I think this would be a really nice addition for the future, that would need an RFC. I'll submit one, when I can find the time for it.

**Comment by pzuraq** [comment]
I’d say wait until the internal refactors calm down, lot’s of things are going to be changing soon, and it may not be possible to do the same things in the same way.
