### ISSUE TITLE
@observes does not expand properties

### ISSUE THREAD

**Issue by jacobq** [ember-decorators/ember-decorators#382]
I noticed that the `@observes` decorator doesn't seem to properly handle braces (as described in the [Ember guides](https://guides.emberjs.com/release/object-model/computed-properties-and-aggregate-data/#toc_multiple-dependent-keys)).

```js
@observes('foo.bar')
obs1() {
  console.log(`obs1 --> ${foo.bar}`); // Fires
}

@observes('foo.{bar}')
obs2() {
  console.log(`obs2 --> ${foo.bar}`); // Does not fire
}

```

@pzuraq Thanks for chatting with me on Discord and working on this issue / whole project.

See also https://github.com/ember-decorators/ember-decorators/pull/275#issuecomment-421066759 and Ember Community Discord server, `#e-decorators` channel, around Wed Jan 16 22:30:00 2019 UTC (not sure how to link to that.... oh well)

**Comment by jacobq** [comment]
Should be fixed by https://github.com/ember-decorators/ember-decorators/pull/383
:tada:

**Comment by jacobq** [comment]
After upgrading to v5.1.0 I get this error message:

```
dist/:95 TypeError: Duplicated element (__EMBER_DECORATORS_FINISH_CHAINS__)
    at _addElementPlacement (my-app.js:25111)
    at _decorateElement (my-app.js:25113)
    at my-app.js:25109
    at Array.forEach (<anonymous>)
    at _decorateClass (my-app.js:25109)
    at _decorate (my-app.js:25091)
    at Module.callback (my-app.js:25149)
    at Module.exports (vendor.js:111)
    at requireModule (vendor.js:32)
    at win.require.args (dist/:89)
```

**Comment by pzuraq** [comment]
Ah, interesting, I know why this is, will release a quick fix

**Comment by jacobq** [comment]
> Ah, interesting, I know why this is, will release a quick fix

Looks like it's in https://github.com/ember-decorators/ember-decorators/pull/386

**Comment by jacobq** [comment]
Works in v5.1.1 :tada: :rocket:
