### ISSUE TITLE
Cannot extend addons, upgrade properly

### ISSUE THREAD

**Issue by allthesignals** [ember-decorators/ember-decorators#391]
I'm in the process of upgrading ember-decorators for a reason I almost forgot: I need to extend an addon that's written in native class syntax in an application that is using the classic object model. 

Here's what happened:
1. I wanted to write a test for my regression bug fix
2. I install ember-test-selectors
3. I realize I need to extend a component provided in an addon, so I do that and use test selectors:

```
  'data-test-layer-group-id': readOnly('tooltip'),
  'data-test-layer-group-active': readOnly('active'),
```

4. throws `class constructors must be invoked with |new|`. I switch to extending via class syntax:

```
  @readOnly('tooltip')
  'data-test-layer-group-id' = null;

  @readOnly('active')
  'data-test-layer-group-active' = null;
```

5. See a runtime terminal error about some babel flag needing to be up. I begin upgrading e-decorators:

```bash
  509  ember install ember-decorators
  510  ember install ember-cli-babel
  511  ember install ember-concurrency-decorators
  512  ember install @ember-decorators/babel-transforms
```
6. `ember s` now gives me a whole message of weird errors:

<img width="607" alt="screen shot 2019-01-28 at 3 35 05 pm" src="https://user-images.githubusercontent.com/5004319/51864999-432ec480-2313-11e9-9126-9385341e3d72.png">

Full stack trace https://gist.github.com/allthesignals/2b789927bdaf4e4cacfec7966ed6a4b3

I'm not sure where to start. I feel like the best advice is to _avoid_ class syntax in addons because it seems like there are issues with common addon features, like extending. 

Maybe this is useful: I have my yarn.lock [here](https://gist.github.com/allthesignals/9e0c2545b43a0d99ec824920c72ecfa2), maybe I have a weird resolution issue.

**Comment by alexlafroscia** [comment]
Is there a reason you have 

```
export default
@classNames('map-container')
class MainMap extends Component {
```

rather than 

```
@classNames('map-container')
export default class MainMap extends Component {
```

?

**Comment by allthesignals** [comment]
> Is there a reason you have
> 
> ```
> export default
> @classNames('map-container')
> class MainMap extends Component {
> ```
> 
> rather than
> 
> ```
> @classNames('map-container')
> export default class MainMap extends Component {
> ```
> 
> ?

Yes, I think it was the proposed syntax at some point - I'm not sure. It sounds like TC39 is going forward with export _before_ decorators, hence why I had it that way. 

> I have also seen it recommended that you should avoid hanging `data-test-*` attributes off of the component, and instead put those in your template. You might want to add a `div` around your component template and set `tagName: ''` to the component itself, and then add your `data-test-*` attributes to that new element.

Who recommends that? It's an approach that's used in the [readme](https://github.com/simplabs/ember-test-selectors). I'll try your approach with tagName, seems easier (but it's not ideal when extending addon components). 

> TC39 is moving forward with `export` before decorators, and that is the stage 2 syntax as is. @allthesignals if you want to opt into export-after, you can with a config variable: https://github.com/ember-decorators/ember-decorators/blob/master/packages/babel-transforms/index.js#L14
> 
> ```js
>   '@ember-decorators/babel-transforms': {
>     decoratorsBeforeExport: false
>   }
> ```
> 
> This will be changing in upcoming versions, assuming TC39 does not change course.

@pzuraq thanks, I went ahead and took @alexlafroscia's advice and just changed back the class decorator syntax to what it should be. 

I got a little further along. 2 thing:

**1. `TypeError: desc is undefined` is thrown in console, here's the [stacktrace]**(https://gist.github.com/allthesignals/c33bf2f6977b9687b3a2566a68363f93). 

Seems to stem from this transpiled application code:
```javascript
define("labs-zola/services/main-map", ["exports", "@babel/runtime/helpers/esm/decorate", "@ember-decorators/object", "ember-concurrency-decorators", "ember-concurrency", "labs-zola/layers/point-layer"], function (_exports, _decorate2, _object, _emberConcurrencyDecorators, _emberConcurrency, _pointLayer) {
  "use strict";

  Object.defineProperty(_exports, "__esModule", {
    value: true
  });
  _exports.default = void 0;
  const DEFAULT_BOUNDS = [-73.9, 40.690913, -73.832692, 40.856654];
  let MainMapService = (0, _decorate2.default)(null, function (_initialize, _EmberService) {
    class MainMapService extends _EmberService {
      constructor(...args) {
        super(...args);

        _initialize(this);
      }

    }
```

**2. There's a flood of "Trace: The node type SpreadProperty has been renamed to SpreadElement"**

Here's the [partial trace](https://gist.github.com/allthesignals/ed7ee23a499435dbf4a77a375e4c62c9).


FWIW, here's my full ember-cli-build:
```javascript
    'ember-cli-babel': {
      includePolyfill: true,
    },
    '@ember-decorators/babel-transforms': {
      decoratorsBeforeExport: true,
    },
    'ember-cli-uglify': {
      uglify: {
        compress: {
          collapse_vars: false,
        },
      },
    },
    babel: {
      plugins: [babelPlugin, 'transform-object-rest-spread'],
    },
    autoImport: {
      webpack: {
        node: {
          fs: 'empty',
        },
      },
    },
    emberCliConcat: {
      js: {
        concat: process.env.EMBER_ENV === 'production',
        useAsync: process.env.EMBER_ENV === 'production',
      },
      css: {
        concat: false,
      },
    },
```

**Comment by alexlafroscia** [comment]
Supporting a decorator as part of `ember-test-selectors` was brought up but the idea ultimately dismissed. The bits I mentioned were what I took away as the justification for not going with that approach. 

https://github.com/simplabs/ember-test-selectors/issues/267#issuecomment-438474872

As for decorators after the export, I was asking because I don’t think that’s the default. I didn’t know (and am sad to hear) that TC39 is planning to make that the real way to handle that case.

**Comment by alexlafroscia** [comment]
What version of `transform-object-rest-spread` are you using? I think that should be something like `@babel/plugin-proposal-object-rest-spread` since you’re likely using Babel 7

https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread

**Comment by allthesignals** [comment]
> Supporting a decorator as part of `ember-test-selectors` was brought up but the idea ultimately dismissed. The bits I mentioned were what I took away as the justification for not going with that approach.
> 
> [simplabs/ember-test-selectors#267 (comment)](https://github.com/simplabs/ember-test-selectors/issues/267#issuecomment-438474872)
> 
> As for decorators after the export, I was asking because I don’t think that’s the default. I didn’t know (and am sad to hear) that TC39 is planning to make that the real way to handle that case.

Gotcha - thanks for digging that up and sharing. Always curious about best practices with testing and test selectors. 

> What version of `transform-object-rest-spread` are you using? I think that should be something like `@babel/plugin-proposal-object-rest-spread` since you’re likely using Babel 7
> 
> https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread

Thanks! I upgraded this dependency. Here's my package.json:
https://gist.github.com/allthesignals/c54bed790d79cc2c37e64503d3ca0298

And my yarn.lock:
https://gist.github.com/allthesignals/18b557d6756307ed6d22cb4cc692f393

I'm still seeing the the[ first problem](https://github.com/ember-decorators/ember-decorators/issues/391#issuecomment-458316608) in the post above:

https://gist.github.com/allthesignals/c33bf2f6977b9687b3a2566a68363f93

In the stack trace, the only application code is here: https://github.com/NYCPlanning/labs-zola/blob/develop/app/services/main-map.js - so I'm confused why I'd be seeing a decorator error, `TypeError: desc is undefined`. Any ideas?

Thanks!

**Comment by allthesignals** [comment]
Here's where I landed:

```
TypeError: decorators[i] is not a function[Learn More] vendor.js:83341:69
	decorateElement http://localhost:4200/assets/vendor.js:83341:69
	decorateClass/< http://localhost:4200/assets/vendor.js:83306:40
	forEach self-hosted:262:13
	decorateClass http://localhost:4200/assets/vendor.js:83304:9
	_decorate http://localhost:4200/assets/vendor.js:83244:21
	<anonymous> http://localhost:4200/assets/labs-zola.js:7256:30
	Module.prototype.exports http://localhost:4200/assets/vendor.js:111:18
	requireModule http://localhost:4200/assets/vendor.js:32:18
	_extractDefaultExport http://localhost:4200/assets/vendor.js:124070:20
	resolveOther http://localhost:4200/assets/vendor.js:123749:27
	resolve http://localhost:4200/assets/vendor.js:123811:20
	_resolve http://localhost:4200/assets/vendor.js:25295:24
	resolve http://localhost:4200/assets/vendor.js:25045:27
	resolve http://localhost:4200/assets/vendor.js:25049:28
	_has http://localhost:4200/assets/vendor.js:25308:16
	has http://localhost:4200/assets/vendor.js:25094:20
	proto.validateInjections http://localhost:4200/assets/vendor.js:25258:28
	create http://localhost:4200/assets/vendor.js:24882:21
	instantiateFactory http://localhost:4200/assets/vendor.js:24752:54
	_lookup http://localhost:4200/assets/vendor.js:24699:16
	lookup http://localhost:4200/assets/vendor.js:24598:20
	lookup http://localhost:4200/assets/vendor.js:45619:14
	Route<._qp< http://localhost:4200/assets/vendor.js:41065:24
	get http://localhost:4200/assets/vendor.js:37463:23
	_get http://localhost:4200/assets/vendor.js:36304:24
	_getQPMeta http://localhost:4200/assets/vendor.js:42939:24
	_fullyScopeQueryParams http://localhost:4200/assets/vendor.js:42995:22
	_processActiveTransitionQueryParams http://localhost:4200/assets/vendor.js:42924:7
	_doTransition http://localhost:4200/assets/vendor.js:42894:7
	transitionTo http://localhost:4200/assets/vendor.js:42611:14
	transitionTo http://localhost:4200/assets/vendor.js:41674:15
	beforeModel http://localhost:4200/assets/labs-zola.js:6408:9
	applyHook http://localhost:4200/assets/vendor.js:53663:16
	runSharedModelHook http://localhost:4200/assets/vendor.js:54116:20
	runBeforeModelHook http://localhost:4200/assets/vendor.js:54090:14
	runBeforeModelHook self-hosted:1018:17
	tryCatcher http://localhost:4200/assets/vendor.js:55681:14
	invokeCallback http://localhost:4200/assets/vendor.js:55853:15
	publish http://localhost:4200/assets/vendor.js:55839:9
	<anonymous> http://localhost:4200/assets/vendor.js:48080:16
	invoke http://localhost:4200/assets/vendor.js:23760:17
	flush http://localhost:4200/assets/vendor.js:23680:25
	flush http://localhost:4200/assets/vendor.js:23839:25
	_end http://localhost:4200/assets/vendor.js:24261:26
	Backburner/this._boundAutorunEnd http://localhost:4200/assets/vendor.js:23996:17
```

After following @buschtoens, suggestion, I used dependency lint. Before, I had many conflicts with babel:
```
labs-zola
├── @ember-decorators/babel-transforms@3.1.5
├─┬ ember-font-awesome
│ └── @ember-decorators/babel-transforms@2.1.2
├─┬ ember-mapbox-composer
│ ├── @ember-decorators/babel-transforms@3.1.5
│ └─┬ ember-font-awesome
│   └── @ember-decorators/babel-transforms@2.1.2
├─┬ labs-ember-search
│ └─┬ ember-font-awesome
│   └── @ember-decorators/babel-transforms@2.1.2
└─┬ labs-ui
  └── @ember-decorators/babel-transforms@3.1.5
```

Now there are no more conflicts there - only one version (3.1.5). 

There are other unrelated conflicts but they different in their patch numbers.

I am seeing the same issue even after `rm -rf node_modules` and `yarn.lock`.

Here's where things have resolved to:
https://gist.github.com/allthesignals/2b4f0d5488017ed4b9f44ea93e6b1b63

https://gist.github.com/allthesignals/d132873d03551bcf4c7154d99a395ec1

**Comment by allthesignals** [comment]
The last error was being generated by how I was incorrectly importing the service decorator. I was saying:

`import { service } from '@ember-decorators/service';`

Instead of 

`import { inject as service } from '@ember-decorators/service';`

!

Closing.

Thanks everyone!
