### ISSUE TITLE
Custom decorators error

### ISSUE THREAD

**Issue by artemgurzhii** [ember-decorators/ember-decorators#396]
**Versions**
 - `ember` -> `3.4.8`
 - `ember-data` -> `3.4.4`
 - `ember-decorators/argument` -> `1.0.0-beta.2`
 - `ember-decorators/babel-transforms` -> `^3.1.0`
 - `ember-decorators` -> `^5.1.2`

**JS Code**

```js
import Service from '@ember/service';
import { inject as service } from '@ember-decorators/service';
import { computed } from '@ember/object';

function computeSomethingByKey(key) {
  return computed('cp1', 'cp2', function() {
    const { cp1, cp2 } = this;

    return this.otherService.fetch({ cp1, cp2, key });
  });
}

export default class ThisService extends Service {
  @service('other/service') otherService;

  cp1 = true;
  cp2 = 'string';

  init() {
    super.init(...arguments);

    // ... init method code
  }

  @computeSomethingByKey('keyX') keyXValue;
  @computeSomethingByKey('keyY') keyYValue;
}
```

**Error message:**
`"Assertion Failed: You attempted to define a '{{link-to "authenticated.nestedRoute.innerNestedRoute"}}' but did not pass the parameters required for generating its dynamic segments. (0 , decorators[i]) is not a function"`

**P.S.** I think this is also something that's needs to be improved in the docs section, to show how custom decorators can be created and explain how to test them/how they will compile & work/etc...

**Comment by buschtoens** [comment]
Can you try this? :)

```diff
-import { computed } from '@ember/object';
+import { computed } from '@ember-decorators/object';
```

**Comment by artemgurzhii** [comment]
@buschtoens Thank you very much for your help, it worked!

Does `computed` imported from the `@ember-decorators/object` intent to work the same as `Ember.Object.computed` would?

The reason I ask is that we have our custom macros(`macros/promise.js` in this case). In some files we don't have decorators yet and have them in others and I just received a new error from the [another place](https://github.com/ember-decorators/ember-decorators/blob/735ec002a35d88a2c1238a3f1c07d80ef86416b8/packages/utils/addon/computed.js#L54) where `this. _computedDesc` is `undefined`.

**Comment by buschtoens** [comment]
`computed` from `@ember-decorators/object` is intended to work exactly as `computed` from `@ember/object`, yes. However, it additionally polyfills the behavior outlined in the Decorators RFC, allowing you to use any `computed` as a decorator as well.

Can you share the code that threw `this. _computedDesc` is `undefined`?

#### Further References

- [RFC #408: Decorators](https://github.com/emberjs/rfcs/blob/master/text/0408-decorators.md)
- [`computed` docs](https://ember-decorators.github.io/ember-decorators/docs/api/modules/@ember-decorators/object#computed)

**Comment by artemgurzhii** [comment]
```js
// app/macros/promise.js
import RSVP from 'rsvp';
import DS from 'ember-data';
import { computed } from '@ember-decorators/object';
import { isPromise } from 'app-name/utils/helpers';

function _promisable(type, ...args) {
  const cb = args.pop();

  return computed(...args, function () {
    let promise = cb.apply(this);

    if (!isPromise(promise)) {
      promise = RSVP.resolve(promise);
    }

    return DS[type].create({ promise });
  });
}

export function promiseArray(...args) { return _promisable('PromiseArray', ...args); }
export function promiseObject(...args) { return _promisable('PromiseObject', ...args); }
```

```js
// app/services/service-with-decorators-which-works.js
import Service from '@ember/service';
import { inject as service } from '@ember-decorators/service';
import { promiseArray } from 'app-name/macros/promise';

function computeSomethingByKey(key) {
  return promiseArray('cp1', 'cp2', function() {
    const { cp1, cp2 } = this;

    return this.otherService.fetch({ cp1, cp2, key });
  });
}

export default class ThisService extends Service {
  @service('other/service') otherService;

  cp1 = true;
  cp2 = 'string';

  init() {
    super.init(...arguments);

    // ... init method code
  }

  @computeSomethingByKey('keyX') keyXValue;
  @computeSomethingByKey('keyY') keyYValue;
}
```

```js
// app/services/service-with-decorators-which-does-not-works.js
import Service from '@ember/service';
import { promiseArray } from 'app-name/macros/promise';

export default Service.extend({
  subscriptions: promiseArray(function () {
    return this.doSomething();
  })
});
```

**Comment by buschtoens** [comment]
Stacktrace? :)

**Comment by artemgurzhii** [comment]
@buschtoens [photo](https://monosnap.com/file/0JNybbryGqEvjiqFWSwSdTJ3g2RblQ)

**Comment by buschtoens** [comment]
Seems like `messaging.js` is the cause; it's missing from the snippets though.

**Comment by artemgurzhii** [comment]
@buschtoens I have updated comment, the `messaging.js` file is the one which does not work, I have other CP property in the same file, in which using new es class getters(`this.subscription`) throws error but `this.get('subscription')` works.

**Comment by buschtoens** [comment]
Just to make sure we're not chasing phantoms here: Can you verify that your are actually consistent with either `subscription` or `subscriptions`? Your code and comments switch between both.

**Comment by artemgurzhii** [comment]
@buschtoens yes, sorry, that was a typo, I'm referencing same `subscriptions` computed property

**Comment by robclancy** [comment]
This error is annoying to get `(0 , decorators[i]) is not a function`. It gives no information on which decorator the issue is from. Usually can be as simple as having the import wrong (eg, most recently I got it because I was importing `service` instead of `inject as service`.
