### ISSUE TITLE
Yarn Workspaces failing to add babel transform plugins

### ISSUE THREAD

**Issue by betocantu93** [ember-decorators/ember-decorators#402]
Currently in a brand new yarn monorepo with "workspaces" with new ember app(s) using `ember-cli-babel` ^7.1.2

The ember-cli-babel > 7.0.0 check fails to pass  
https://github.com/ember-decorators/ember-decorators/blob/23c55cc279f1e3715a742836a55c74883042feaa/packages/babel-transforms/index.js#L24

so the plugins 
`@babel/plugin-proposal-decorators` and `@babel/plugin-proposal-class-properties`
don't get added.

I made a repro repo
https://github.com/betocantu93/monorepo-decorators

Currently the workaround that worked for me is using `nohoist`. We need to add to the app(s) package.json the following
```
"workspaces": {
    "nohoist": [
      "ember-decorators", 
      "ember-decorators/**", 
      "@ember-decorators/babel-transforms", 
      "@ember-decorators/babel-transforms/**", 
      "ember-cli-dependency-checker", 
      "ember-cli-dependency-checker/**"
    ]
  },
```

**Comment by mike-north** [comment]
related: https://github.com/ember-cli/ember-cli-version-checker/issues/93

**Comment by buschtoens** [comment]
Closing as the underlying issue https://github.com/ember-cli/ember-cli-version-checker/issues/93 / https://github.com/ember-cli/ember-cli-version-checker/issues/70 was fixed and as this was affecting now majorly outdated versions.
