### ISSUE TITLE
@service router is undefined

### ISSUE THREAD

**Issue by ballPointPenguin** [ember-decorators/ember-decorators#420]
I'm not sure if this is the right place for this issue.

```
import Component from '@glimmer/component'
import { inject as service } from '@ember-decorators/service'

export default class AlienFrameComponent extends Component {
  @service router
}
```

router is undefined.

**Comment by ballPointPenguin** [comment]
aha 🦆 
I needed to use
`this.get('router')`
instead of
`this.router`

**Comment by pzuraq** [comment]
That should not be the case, which version of Ember are you using?

**Comment by pgrippi** [comment]
@pzuraq I've run into this as well, testing the latest Ember Octane.

```
"ember-source": "https://s3.amazonaws.com/builds.emberjs.com/canary/shas/707a938e536cb921dbe80ee270c431d1b9717e38.tgz",
"ember-decorators": "5.1.4",
```

All ES6 classes are affected it looks like; doesn't matter what Ember class it extends from (EmberObject, Route, Controller, Service, and Component are the ones I've run into it with)

**Comment by pzuraq** [comment]
@pgrippi can you provide the version of `@ember-decorators/babel-transforms` you are using? And if it’s not too much trouble, the code of the class itself? That would help a bit in figuring this out

**Comment by pgrippi** [comment]
Sure, I'm using (figure it can't hurt to throw the babel version in too):

```
"@ember-decorators/babel-transforms": "5.1.4"
"ember-cli-babel": "7.6.0"
```

As for the code, the simplest case is in my application router:

```
import Route from '@ember/routing/route';
import { inject as service } from '@ember-decorators/service';

export default class ApplicationRoute extends Route {
  @service router;

  init() {
    super.init(...arguments);

    this.router.on('routeDidChange', () => {
      console.debug('route did change');
    });
  }
}
```

**Comment by pzuraq** [comment]
alright, I'll see if I can get a reproduction going. For reference, you should be using the _stage 1_ versions of the transforms:

```js
"@ember-decorators/babel-transforms": "2.1.2"
```

We're working on baking these into `ember-cli` at the moment, I realize this is confusing. If you use the stage 1 transforms, do you have the same problem?

**Comment by pgrippi** [comment]
Is there anything else I have to do to use stage 1 other than downgrade `@ember-decorators/babel-transforms` to 2.1.2? After downgrading to 2.1.2 I still see the issue

**Comment by pzuraq** [comment]
I believe this should be fixed on the latest ember-decorators, with the polyfill. Let us know if not!
