### ISSUE TITLE
ember-data decorators

### ISSUE THREAD

**Issue by XuluWarrior** [ember-decorators/ember-decorators#436]
`ember-decorators@6.0.0` has removed the `@ember-decorators/data` package.  I am rather unclear as to whether there is still a way to use the decorators that this package provided.

I have installed `ember-decorators-polyfill` but that doesn't polyfill the `ember-data` properties.
I've also tried installing `@ember-decorators/data` from npm but this seems to be incompatible with `ember-decorators@6.0.0`.

Is there a way now or upcoming that will allow our project to continue using the `ember-data` decorators?

**Comment by pzuraq** [comment]
In the latest version of Ember, and with the polyfill provided by Ember, `DS.attr`, `DS.hasMany`, and `DS.belongsTo` are decorators:

```js
class Person extends DS.Model {
  @DS.attr() name;
}
```

You must use parens currently, but other than that everything should work. The general principle is that all computed property _macros_ (functions that return computed properties) now return decorators. `DS.attr` returns a computed property macro, which is a decorator, so it all works 😄

**Comment by XuluWarrior** [comment]
@pzuraq Thank you for your very prompt reply.
I think my problem was that I had decorators without parentheses.  When I tried it again, it worked as expected.
