### ISSUE TITLE
Question: why is @ember-decorators/babel-transforms still referenced in v6?

### ISSUE THREAD

**Issue by jacobq** [ember-decorators/ember-decorators#439]
I know they're just devDeps, and I'm not seeing any problems from this, but I am trying to understand why these weren't removed in v6:

1. https://github.com/ember-decorators/ember-decorators/blob/f3a2fb509bcdf952599e311b75e029a322541ebe/config/ember-try.js#L78

2. https://github.com/ember-decorators/ember-decorators/blob/e74762560dbfb1202b73ab4ec01a40913650fab1/packages/object/package.json#L31

3. https://github.com/ember-decorators/ember-decorators/blob/e74762560dbfb1202b73ab4ec01a40913650fab1/packages/utils/package.json#L27

4. https://github.com/ember-decorators/ember-decorators/blob/f3a2fb509bcdf952599e311b75e029a322541ebe/packages/-ember-decorators/ember-cli-build.js#L43-L45

5. https://github.com/ember-decorators/ember-decorators/blob/e74762560dbfb1202b73ab4ec01a40913650fab1/packages/component/package.json#L32

**Comment by pzuraq** [comment]
Ah, this was a mistake, they should be removed. They aren't used in the build process, so it didn't catch them.

**Comment by jacobq** [comment]
Got it. (I just chanced across this when chasing down another warning.)
