### ISSUE TITLE
attribute component decorator receiving array instead of string

### ISSUE THREAD

**Issue by dustinsoftware** [ember-decorators/ember-decorators#441]
```
    "@ember-decorators/component": "^6.0.0",
    "ember-cli-babel": "^7.7.3",
    "ember-decorators-polyfill": "^1.0.4",
    "ember-source": "~3.8.0",
```
In a component:
```ts
import { attribute } from '@ember-decorators/component';

export default class Button extends Component {
  @attribute('data-test-button')
  @computed('elementId', 'testSelector')
  get dataTestButton(): string {
    return this.testSelector || this.elementId;
  }
```

Behavior at runtime:
![image](https://user-images.githubusercontent.com/942358/57168996-61a0d200-6dd2-11e9-9c64-153889191e77.png)

![image](https://user-images.githubusercontent.com/942358/57169014-70878480-6dd2-11e9-84da-dc6c68731c19.png)

Not entirely sure why the decorator is expecting a string instead of an array, maybe my babel configuration isn't compiling the decorators properly? Any ideas here?

**Comment by buschtoens** [comment]
From your screenshot of `decoratorWithParams` I could tell that you are getting bundled an outdated version of `@ember-decorators/utils`.

https://github.com/ember-decorators/ember-decorators/blob/v5.1.4/packages/utils/addon/decorator.js#L85-L94

Please install [`ember-cli-dependency-lint`](https://github.com/salsify/ember-cli-dependency-lint) and check what addon is including an outdated version of `utils` as a dependency.

**Comment by dustinsoftware** [comment]
Wow, that was it. `ember-css-modules` was pulling in an old version of `@ember-decorators/utils`. I've installed the dependency linter like you suggested so we don't encounter this again, thanks so much...
