### ISSUE TITLE
`@layout` decorator doesn't work in ember addon

### ISSUE THREAD

**Issue by nightire** [ember-decorators/ember-decorators#445]
I use `@layout` decorator in ember addon like this:

``` javascript
import { attribute, layout } from '@ember-decorators/component';
import Component from '@ember/component';

import template from '../templates/components/my-addon';

@layout(template)
class MyAddonComponent extends Component {
}

export default MyAddonComponent;
```

and it throws an error:

<details>
<summary>TypeError: Cannot set property 'layout' of undefined</summary>

```
    at index.js:166
    at decorator.js:97
    at decorator.js:22
    at Module.callback (vendor.js:63646)
    at Module.exports (loader.js:106)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
    at Module.exports (loader.js:104)
    at requireModule (loader.js:27)
    at Class._extractDefaultExport (index.js:422)
```

</details>

These are the dependencies I used:

```
  "ember-cli-babel": "~7.7.3"
  "ember-decorators": "~6.0.0"
  "ember-source": "~3.10.0"
```

currently, I use `MyAddonComponent.prototye.layout = template;` to make it work, but later I found that `@attribute` decorator doesn't work as well. It doesn't throw any error, just no effect at all.

**Comment by nightire** [comment]
Okay, I found the root cause, is the `ember-concurrency-decorators`. If I upgrade it to `~1.0.0-beta.2` or remove it, `@layout` and `@attribute` will work well.

**Comment by buschtoens** [comment]
This is caused by e-c-d depending on `@ember-decorators/utils@5`. The `1.0.0-beta` depends on `@6`. Please install `ember-cli-dependency-lint` to catch these kinds of errors.

I think we should add a note about this to the docs. This kind of issue is happening _way_ too often.

**Comment by rwjblue** [comment]
Ya we could also detect and issue a warning

**Comment by nightire** [comment]
> Please install `ember-cli-dependency-lint` to catch these kinds of errors.

Nice, thanks for the tip.

**Comment by buschtoens** [comment]
Tracking in #447 (docs) and #448 (detection).
