### ISSUE TITLE
5.1.4 / 5.2.0 not compatible with iOS 9.3.5

### ISSUE THREAD

**Issue by elgordino** [ember-decorators/ember-decorators#446]
In this commit an inner function declaration was added:

https://github.com/ember-decorators/ember-decorators/pull/398/commits/010148d1e4927fc8f398fa8fba5db40713af1d59#diff-895236f0cac2b26a4d31edfa36001bbeR72 (line 72)

This results in an error in Safari in iOS 9.3.5 saying 'Strict mode does not allow function declarations in a lexically nested statement.'

Is it possible to consider an update to the 5.x branch with this refactored to not perform the declarations in this manner? I could probably submit a PR to do so if that would be desired?

I appreciate iOS 9 is probably not the top of the stack of supported browsers, but this is the only issue in my project preventing ember from working. I've rolled back to 5.1.2 for now.

**Comment by buschtoens** [comment]
Related to #417 / #440, in that they also target a browser incompatibility for the `5.x` series.

Out of curiosity, may I ask what is keeping you from upgrading to `6.x.` / stage 1 decorators?

**Comment by elgordino** [comment]
Thanks @buschtoens. At the moment we are stuck on Ember 3.4, something has changed with how computed properties work in subsequent releases. I'm yet to figure out what the underlying problem is.

**Comment by elgordino** [comment]
Closing this as I was able to move to Ember 3.12 and use 6.x decorators.
