### ISSUE TITLE
Add @classNameBindings and @attributeBindings class decorators

### ISSUE THREAD

**Issue by pzuraq** [ember-decorators/ember-decorators#450]
Currently, it's not possible to directly convert certain bindings because dynamic properties cannot be decorated. Adding two class decorators to specify the values directly would prevent this from being an issue. This will also be a much easier to target output for the codemod.

**Comment by teopalva** [comment]
+1. Running the codemod deleted my original classNameBindings without replacing them. What is the recommended way to support classNameBindings-like behavior with decorators?

**Comment by pzuraq** [comment]
At the moment, it's using the `@className` and `@attribute` decorators. We'll be updating the codemod to use these class decorators once we get them shipped.
