### ISSUE TITLE
Filter array based on another property?

### ISSUE THREAD

**Issue by nwhittaker** [ember-decorators/ember-decorators#64]
Is there an equivalent way to filter an array when another property changes? Something that achieves the same thing as:

``` javascript
someItems: computed.filter('allItems', function(item) {
   return item.indexOf(this.get('filterText')) > -1;
}).property('filterText');
```

**EDIT:** Fix property to call `computed.filter()`, instead of `computed()`.

**Comment by chrishowes** [comment]
+1

**Comment by pzuraq** [comment]
Do you mean something more like one of these?

```
someItems: computed('allItems', 'filterText', function(items, filterText) {
  return items.filter(i => i.indexOf(filterText) > -1);
})
```

or

```
someItems: filter('allItems', function(item) {
   return item.indexOf(this.get('filterText')) > -1;
}).property('filterText');
```

Not sure how the original syntax would work

**Comment by nwhittaker** [comment]
Sorry, yes. I meant `computed.filter()`. I'll edit the description.

**Comment by pzuraq** [comment]
Will have to look more into how that worked originally, but we may be able to get that to work once we get composeable computeds working too

**Comment by pzuraq** [comment]
We now have an open RFC which would address this issue by adding the ability to pass additional dependent keys to the affected computed macros, you can check it out [here](https://github.com/emberjs/rfcs/pull/375). Closing this issue for now.
