### ISSUE TITLE
Syntax errors with object rest spread

### ISSUE THREAD

**Issue by redbmk** [ember-decorators/ember-decorators#74]
If you use object rest spread (`...{ asdf: 'zxcv' }`) in the same object as a `@computed` decorator you'll get some weird behavior. The first time it compiles I get this error:

```
The Broccoli Plugin: [StubGenerator] failed with:
Error: Error parsing code while looking for "npm:" imports: SyntaxError: Unexpected token (97:2)
```

If i write the same file without any changes, then it will compile without any errors, but produces a syntax error, trying to replace the spreaded object with `{ key: }`.
#### source

```
import Ember from 'ember';
import computed from 'ember-computed-decorators';

function generateProps(name, defaultValue) {
  let props = {};

  props[name] = defaultValue;
  props[`tenTimes${name.capitalize()}`] = 10 * defaultValue;

  return props;
}

export default Ember.Component.extend({
  four: 4,
  ...generateProps('five', 5),
  ...generateProps('six', 6),

  @computed('six')
  seven(six) {
    return six + 1;
  }
});
```
#### generated

```
define(/*...*/ {
  //function _createDecoratedObject...
  function generateProps(name, defaultValue) {
    var props = {};

    props[name] = defaultValue;
    props['tenTimes' + name.capitalize()] = 10 * defaultValue;

    return props;
  }

  exports['default'] = _ember['default'].Component.extend(_createDecoratedObject([{
    key: 'four',
    initializer: function initializer() {
      return 4;
    }
  }, {
    key:
  }, {
    key: 'seven',
    decorators: [(0, _emberComputedDecorators['default'])('six')],
    value: function seven(six) {
      return six + 1;
    }
  }]));
});
```

If I replace the `@comptued` decorator with `seven: Ember.computed('six', function() { return this.get('six') + 1; }`, then I get the following:

```
  exports['default'] = _ember['default'].Component.extend(_extends({
    four: 4
  }, generateProps('five', 5), generateProps('six', 6), {

    seven: _ember['default'].computed('six', function () {
      return this.get('six') + 1;
    })
  }));
```

**Comment by pzuraq** [comment]
This is likely a problem with the babel transforms themselves. Are you still encountering this issue on Babel 6/latest?

**Comment by redbmk** [comment]
I hadn't looked at this in a while - looks like things have changed a bit. Using the latest version of `ember-cli` and `ember-decorators`, the above code seems to work fine (the main difference being the import is now `import { computed } from 'ember-decorators/object'`
